name: Main Checks

on:
  push:
    branches:
      - main
      - "v*.*.*"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
